## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tasklistdb
    username: postgres
    password: password
  jpa:
    properties:
      hibernate:
        # The SQL dialect makes Hibernate generate better SQL for the chosen database
        dialect: org.hibernate.dialect.PostgreSQLDialect
        # Hibernate ddl auto (create, create-drop, validate, update)
        hbm2ddl:
          auto: update
        temp:
          #https://vkuzel.com/spring-boot-jpa-hibernate-atomikos-postgresql-exception
          use_jdbc_metadata_defaults: false
          # https://vkuzel.com/spring-boot-jpa-hibernate-atomikos-postgresql-exception
    database-platform: hibernate.dialect.PostgreSQL10Dialiect
    show-sql: true
    generate-ddl: true
  h2:
    console:
      enabled: false
  data:
    rest:
      base-path: /api




